# Generated by Django 5.2.9 on 2025-12-02 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📦', help_text='Emoji or icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('website_url', models.URLField()),
                ('logo_url', models.URLField(blank=True, help_text='URL to merchant logo image')),
                ('description', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='URL to product image')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(blank=True, help_text='Product SKU/ID', max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Lowest price found', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shoplio_app.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('affiliate_link', models.URLField(help_text='Affiliate link for this product-merchant combination')),
                ('product_url', models.URLField(help_text='Direct product page URL')),
                ('in_stock', models.BooleanField(default=True)),
                ('availability_text', models.CharField(default='In Stock', max_length=100)),
                ('click_count', models.IntegerField(default=0, help_text='Number of clicks on affiliate link')),
                ('is_active', models.BooleanField(default=True)),
                ('last_price_update', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='shoplio_app.merchant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_links', to='shoplio_app.product')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('product', 'merchant')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('verified_purchase', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shoplio_app.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('product_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shoplio_app.productmerchant')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['-clicked_at'], name='shoplio_app_clicked_2162aa_idx'), models.Index(fields=['product_merchant'], name='shoplio_app_product_113d4b_idx')],
            },
        ),
    ]
