# Generated by Django 5.2.9 on 2025-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplio_app', '0002_product_admin_notes_product_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_svg',
            field=models.CharField(blank=True, help_text='SVG icon filename (e.g., category-electronics.svg)', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to category banner image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
    ]
