# Generated by Django 4.2.7 on 2025-12-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoplio_app', '0004_banner_remove_category_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_code', models.CharField(help_text='Unique code for affiliate links', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('paypal', 'PayPal'), ('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash')], default='bank', max_length=50)),
                ('payment_details', models.TextField(help_text='Bank account number, PayPal email, etc.')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve affiliate')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_affiliates', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate',
                'verbose_name_plural': 'Affiliates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickBankProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('vendor', models.CharField(help_text='ClickBank vendor name', max_length=100)),
                ('hoplink', models.URLField(help_text='ClickBank HopLink (affiliate tracking URL)')),
                ('product_image_url', models.URLField(blank=True, help_text='External image URL for product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission percentage (e.g., 75.00 for 75%)', max_digits=5)),
                ('estimated_commission', models.DecimalField(decimal_places=2, help_text='Estimated commission per sale', max_digits=10)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('click_count', models.IntegerField(default=0, help_text='Total clicks on this product')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clickbank_products', to='shoplio_app.category')),
            ],
            options={
                'verbose_name': 'ClickBank Product',
                'verbose_name_plural': 'ClickBank Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='affiliate',
            field=models.ForeignKey(blank=True, help_text='Affiliate who referred this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shoplio_app.affiliate'),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission percentage at time of sale', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='shoplio_app.affiliate')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='shoplio_app.order')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='shoplio_app_created_7972e3_idx'), models.Index(fields=['affiliate', 'status'], name='shoplio_app_affilia_b3f879_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClickBankClickTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('clickbank_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shoplio_app.clickbankproduct')),
            ],
            options={
                'verbose_name': 'ClickBank Click',
                'verbose_name_plural': 'ClickBank Clicks',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['-clicked_at'], name='shoplio_app_clicked_fd55d3_idx'), models.Index(fields=['clickbank_product'], name='shoplio_app_clickba_77e85b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('converted', models.BooleanField(default=False, help_text='Did this click result in a sale?')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shoplio_app.affiliate')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_click', to='shoplio_app.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_clicks', to='shoplio_app.product')),
            ],
            options={
                'verbose_name': 'Affiliate Click',
                'verbose_name_plural': 'Affiliate Clicks',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['-clicked_at'], name='shoplio_app_clicked_01680b_idx'), models.Index(fields=['affiliate'], name='shoplio_app_affilia_a761cf_idx'), models.Index(fields=['converted'], name='shoplio_app_convert_a5f271_idx')],
            },
        ),
    ]
